
ex1: ex1.c stub1.o
	gcc ex1.c stub1.o -o ex1

ex2: ex2.c stub2.o
	gcc ex2.c stub2.o -o ex2

ex3: ex3.c stub3.o
	gcc ex3.c stub3.o -o ex3

ex4: ex4.c stub4.o
	gcc ex4.c stub4.o -o ex4


test_ex1: ex1
	./ex1

test_ex2: ex2
	./ex2

test_ex3: ex3
	./ex3

test_ex4: ex4
	./ex4

clean:
	rm -f ex1 ex2 ex3 ex4
